<!doctype html>
<html lang="en">
<head>
    <script src="/js/clock.js"></script>
</head>
<body>

<div id="js-clock-widget">
    <span class="js-hours">
        <span>hh: </span><span class="js-value">11</span>
    </span>

    <span class="js-minutes">
        <span>mm: </span><span class="js-value">22</span>
    </span>

    <span class="js-seconds">
        <span>ss: </span><span class="js-value">44</span>
    </span>

    <span class="js-milliseconds">
        <span>ms: </span><span class="js-value">33</span>
    </span>
</div>

</body>
</html>